services:
  backend:
    image: oncu-backend:prod
    build:
      context: ./server
      dockerfile: Dockerfile
      # ports:
      #   - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
        - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1453Abdullah*
      - DB_NAME=oncu
      - PORT=8082
      - CORS_ORIGIN=https://imamhatipsporoyunlari.com
      - UPLOAD_DIR=uploads
    volumes:
      - ./server:/app
      - /app/node_modules
        - ./server/uploads:/app/uploads
    networks:
      - oncu-network
    restart: unless-stopped

  frontend:
    image: oncu-frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # ports:
      #   - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://imamhatipsporoyunlari.com
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - oncu-network
    restart: unless-stopped

  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1453Abdullah*
      MYSQL_DATABASE: oncu
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p1453Abdullah*",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      # ports:
      #   - "3306:3306"
    networks:
      - oncu-network
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  #  phpmyadmin:
  #    container_name: oncu_phpmyadmin
  #    image: phpmyadmin/phpmyadmin
  #    ports:
  #      - "8053:80"
  #    environment:
  #      PMA_HOST: mysql
  #      PMA_USER: root
  #      PMA_PASSWORD: 1453Abdullah*
  #    depends_on:
  #      - db
  #  networks:
  #    - oncu-network
  #  restart: unless-stopped

  nginx:
    container_name: oncu_nginx
    image: nginx:latest
    ports:
      - "8140:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - oncu-network
networks:
  oncu-network:
    name: oncu-network

volumes:
  frontend:
  db:
